BOT_TOKEN: 
  - NzE5MDg1MzY0MDE4NDEzNTcw.GwnkDo.E4v40kP35o1ikLl4chWGThQpTerWgpCQvf0pmM
CHANNEL_ID: 
  - 1109640951456079892
  - 1109640954371113002
MODE: custom
REPLY: Y
SIMSIMI_LANG: en
DELAY: 100
DEL_AFTER: 
REPOST_LAST_CHAT: 100